### ISSUE TITLE
Error during displaying a custom control.

### ISSUE THREAD

**Issue by krystofair** [mhanzel/Skrzynia_bieg-w_V2#2]
We (I & @Fiko99) encounter on error when we try to see Form2[Designer] in VS.

**Comment by Christofair** [comment]
![image](https://user-images.githubusercontent.com/33362868/122793109-19e3aa00-d2bb-11eb-89a0-0aab541c2282.png)

**Comment by mhanzel** [comment]
Did u check, do simulation working?

**Comment by Christofair** [comment]
This isn't our issue, we want to develop app and we cant.
